### ISSUE TITLE
Not working for me. Nothin Happens but script is running in taper monkey.

### ISSUE THREAD

**Issue by shad90** [ruia/SonarrExternalPlayer#1]
I don't have much knowledge but i think the problem is here
`var ficheiro = jQuery(".EpisodeSummary-fileRow-3brC7").children().first().text();`  

running this in console doesn't give any thing. 
May be you can work it out 
Thx

**Comment by ruia** [comment]
Hi, 

This was kinda in abandonware since i moved my media to an external server and use Plex player to watch it. 
I updated the code and tested its working as of version 2.0.0.5344 of Sonarr.
Toaster notification didnt work for me but maybe its some kind of extension on my part.

Please try and let me now.
Dont forget you need the external agent (https://github.com/Kayomani/PlexExternalPlayer/releases)

Thanks
Rui

**Comment by shad90** [comment]
Thanks for quick response.
I am still facing some problem.
 
Now script is working fine. Play button appears and console shows this message
`Refused to connect to "http://localhost:7251/?protocol=2&item=D%3A%5CDownloads%5CDocumentaries%5CDocumentary%20Shows%5CThe%20Truth%20About%5CSeason%2001%5CThe%20Truth%20About.%20-%20S01E06%20-%20Your%20Teeth%20-%20Part%202%20HDTV-720p.mkv": URL is not a part of the @connect list`
and Plex Externa Player agent isn't picking anything or playing anything. 

If I click on this url in console it plays the file in external player as it should be. 

`@connect     http://localhost:7251/`    is still in script but still it isn't working

**Edit:** changing `@connect     http://localhost:7251/`   **to**  `@connect     *`   is doing the trick as in original Plex External Player Script but is it good practice ?

_Edit 2:_
**It is working !!**  
From This [Issue opened forTapermonkey](https://github.com/Tampermonkey/tampermonkey/issues/262) i got the info that changing from `@connect     http://localhost:7251/`  **to** `@connect     localhost`  **or** `@connect     *`  should work and is working.

Thnx

**Comment by ruia** [comment]
Glad it worked!

If i have the time, i will try to also add a buttons directly on the main page of the show.

Best regards
Rui

**Comment by shad90** [comment]
That will be better thing. Now I can uninstall plex because i don't need server for single machine. I just need sonarr and media player.
